### ISSUE TITLE
JS error on running getting started 

### ISSUE THREAD

**Issue by happykhan** [abschneider/StrainHub#5]
![image](https://user-images.githubusercontent.com/1452696/144271901-35628f75-caa0-43fb-ae0e-a66917a3a548.png)

Hi, 

Have followed instructions to run via docker. 

Getting an error to console when clicking on "get started. " I am running nginx (reverse proxy) to give me access to the 3838 port, would this be a problem ?

Cheers

**Comment by abschneider** [comment]
Old, no response. Closed.
